// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:notepad/models/grocery_item.dart';
import 'package:notepad/models/note.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GroceryItemAdapter());
    registerAdapter(NoteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GroceryItemAdapter());
    registerAdapter(NoteAdapter());
  }
}
