// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:notepad/models/checklist.dart';
import 'package:notepad/models/checklist_item.dart';
import 'package:notepad/models/note.dart';
import 'package:notepad/models/reminder.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChecklistAdapter());
    registerAdapter(ChecklistItemAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(ReminderAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChecklistAdapter());
    registerAdapter(ChecklistItemAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(ReminderAdapter());
  }
}
